Traceback (most recent call last):
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Define the nodes
n=100                  # solving with 100 nodes
x=np.linspace(0,1,n)   # on the domain [0,1]
h = x[1]-x[0]          # size of each interval

# Implement starting conditions
y=np.zeros(n)
y[0]=1
y[1]=1

# Implement finite difference rule
for k in range(0,n-2):
  y[k+2]=(2-h)*y[k+1]+(6*h**2+h-1)*y[k]

# Compare to analytic solution
fig,ax = plt.subplots(1,2)
ax[0].plot(x,y)
ax[0].set_title('Solution')
ysol = (2*np.exp(-3*x) + 3*np.exp(2*x))/5
ax[1].plot(x,abs((y.T-ysol).T))
ax[1].set_title('Error')
plt.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-1-45c705026f86>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Define the nodes[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [0mn[0m[1;33m=[0m[1;36m100[0m                  [1;31m# solving with 100 nodes[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 3[1;33m [0mx[0m[1;33m=[0m[0mnp[0m[1;33m.[0m[0mlinspace[0m[1;33m([0m[1;36m0[0m[1;33m,[0m[1;36m1[0m[1;33m,[0m[0mn[0m[1;33m)[0m   [1;31m# on the domain [0,1][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [0mh[0m [1;33m=[0m [0mx[0m[1;33m[[0m[1;36m1[0m[1;33m][0m[1;33m-[0m[0mx[0m[1;33m[[0m[1;36m0[0m[1;33m][0m          [1;31m# size of each interval[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

