Traceback (most recent call last):
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\ella metcalfe\anaconda3\envs\py37\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Initial guess
xguess= 0.2
tol = 10**(-7)
f = lambda x: cos(x)

while 1:
    x = f(xguess)
    if abs(x-xguess)<tol:
        break
    else:
        xguess = x

print('FP root: {:.12f}'.format(x))

xx = fsolve(lambda x: (x-cos(x)), 0.2)
print('NR root: {:.12f}'.format(xx[0]))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-8-e5f911bf6264>[0m in [0;36m<module>[1;34m[0m
[0;32m      5[0m [1;33m[0m[0m
[0;32m      6[0m [1;32mwhile[0m [1;36m1[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 7[1;33m     [0mx[0m [1;33m=[0m [0mf[0m[1;33m([0m[0mxguess[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      8[0m     [1;32mif[0m [0mabs[0m[1;33m([0m[0mx[0m[1;33m-[0m[0mxguess[0m[1;33m)[0m[1;33m<[0m[0mtol[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      9[0m         [1;32mbreak[0m[1;33m[0m[1;33m[0m[0m

[1;32m<ipython-input-8-e5f911bf6264>[0m in [0;36m<lambda>[1;34m(x)[0m
[0;32m      2[0m [0mxguess[0m[1;33m=[0m [1;36m0.2[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [0mtol[0m [1;33m=[0m [1;36m10[0m[1;33m**[0m[1;33m([0m[1;33m-[0m[1;36m7[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 4[1;33m [0mf[0m [1;33m=[0m [1;32mlambda[0m [0mx[0m[1;33m:[0m [0mcos[0m[1;33m([0m[0mx[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [1;33m[0m[0m
[0;32m      6[0m [1;32mwhile[0m [1;36m1[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'cos' is not defined
NameError: name 'cos' is not defined

